CREATE VIEW vista_produtos_enviados_total AS
SELECT
    gv.ID_GUIAVENDAS,
    gv.DATA_GUIAVENDAS AS data_guiasvendas,
    gv.ID_ARMAZEM,
    e.ID_EQUIP,
    e.NOME_EQUIP
FROM
    GUIAREMESSAVENDAS gv
JOIN
    FATURA f ON gv.ID_GUIAVENDAS = f.ID_GUIAVENDAS
JOIN
    EQUIPAMENTOS_FATURA ef ON f.ID_FATURA = ef.ID_FATURA
JOIN
    EQUIPAMENTOS e ON ef.ID_EQUIP = e.ID_EQUIP;
