# Generated by Django 3.1.12 on 2025-02-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id_armazem', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_armazem', models.TextField()),
                ('morada_armazem', models.TextField()),
                ('email_armazem', models.TextField()),
                ('contacto_armazem', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
            options={
                'db_table': 'armazem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriacomponentes',
            fields=[
                ('id_catcomponentes', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_catcomponentes', models.TextField()),
                ('descricao_catcomponentes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoriacomponentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cliente', models.TextField()),
                ('datanasc_cliente', models.DateField()),
                ('morada_cliente', models.TextField()),
                ('nif_cliente', models.IntegerField()),
                ('email_cliente', models.TextField()),
                ('contacto_cliente', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id_componente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_componente', models.TextField()),
                ('descricao_componente', models.TextField(blank=True, null=True)),
                ('precomedio_componente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'componentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encomendas',
            fields=[
                ('id_encomenda', models.IntegerField(primary_key=True, serialize=False)),
                ('data_encomenda', models.DateField()),
            ],
            options={
                'db_table': 'encomendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id_equip', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_equip', models.TextField()),
                ('desc_equip', models.TextField(blank=True, null=True)),
                ('custo_equip', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'equipamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id_fatura', models.IntegerField(primary_key=True, serialize=False)),
                ('preco_fatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_fatura', models.DateField()),
            ],
            options={
                'db_table': 'fatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.TextField()),
                ('morada_fornecedor', models.TextField()),
                ('email_fornecedor', models.TextField()),
                ('contacto_fornecedor', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
            options={
                'db_table': 'fornecedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guiaremessacompras',
            fields=[
                ('id_guiacompras', models.IntegerField(primary_key=True, serialize=False)),
                ('data_guiacompras', models.DateField()),
            ],
            options={
                'db_table': 'guiaremessacompras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guiaremessavendas',
            fields=[
                ('id_guiavendas', models.IntegerField(primary_key=True, serialize=False)),
                ('data_guiavendas', models.DateField()),
            ],
            options={
                'db_table': 'guiaremessavendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maodeobra',
            fields=[
                ('id_mo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_mo', models.TextField()),
                ('desc_mo', models.TextField(blank=True, null=True)),
                ('custo_mo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'maodeobra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoequipamentos',
            fields=[
                ('id_tipoequip', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_tipoequip', models.TextField()),
                ('desc_tipoequip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoequipamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='acesso_pgestao',
            fields=[
                ('id_utilpgestao', models.IntegerField(primary_key=True, serialize=False)),
                ('password_pgestao', models.CharField(max_length=50)),
                ('id_nivel', models.IntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2')], default=2)),
            ],
            options={
                'db_table': 'acesso_pgestao',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equip_pgsidcampo', models.CharField(max_length=100)),
                ('desc_equip_pgsidcampo', models.TextField()),
                ('custo_equip_pgsidcampo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_url', models.URLField()),
            ],
            options={
                'db_table': 'EQUIPAMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('timestamp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'COMPRAS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=20)),
                ('telemovel', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('morada', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EncomendasComponentes',
            fields=[
                ('id_encomenda', models.OneToOneField(db_column='id_encomenda', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BD_2.encomendas')),
                ('quantidade_ec', models.IntegerField()),
                ('precounidade_ec', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'encomendas_componentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentosFatura',
            fields=[
                ('id_fatura', models.OneToOneField(db_column='id_fatura', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BD_2.fatura')),
                ('quantidade_equipfatura', models.IntegerField()),
            ],
            options={
                'db_table': 'equipamentos_fatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FornecedoresComponentes',
            fields=[
                ('id_componente', models.OneToOneField(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BD_2.componentes')),
            ],
            options={
                'db_table': 'fornecedores_componentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receitaequip',
            fields=[
                ('id_equip', models.OneToOneField(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BD_2.equipamentos')),
                ('quantidade_receita', models.IntegerField()),
            ],
            options={
                'db_table': 'receitaequip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockcomponentes',
            fields=[
                ('id_armazem', models.OneToOneField(db_column='id_armazem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BD_2.armazem')),
                ('quantidade_stockcomp', models.IntegerField()),
            ],
            options={
                'db_table': 'stockcomponentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockequipamentos',
            fields=[
                ('id_armazem', models.OneToOneField(db_column='id_armazem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BD_2.armazem')),
                ('quantidade_stockequip', models.IntegerField()),
            ],
            options={
                'db_table': 'stockequipamentos',
                'managed': False,
            },
        ),
    ]
