-- Create
CREATE OR REPLACE PROCEDURE sp_Acesso_pgestao_create(p_ID_FUNCIONARIO INT4, p_ID_NIVEL INT4, p_PASSWORD_PGESTAO TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO ACESSO_PGESTAO(ID_FUNCIONARIO, ID_NIVEL, PASSWORD_PGESTAO)
    VALUES (p_ID_FUNCIONARIO, p_ID_NIVEL, p_PASSWORD_PGESTAO);
    RAISE NOTICE 'Acesso à plataforma de gestão criado';
END;
$$;

-- Read
CREATE OR REPLACE PROCEDURE sp_Acesso_pgestao_read(p_ID_UTILPGESTAO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_FUNCIONARIO, ID_NIVEL, PASSWORD_PGESTAO
    FROM ACESSO_PGESTAO
    WHERE ID_UTILPGESTAO = p_ID_UTILPGESTAO;
END;
$$;

-- Update
CREATE OR REPLACE PROCEDURE sp_Acesso_pgestao_update(p_ID_UTILPGESTAO INT4, p_ID_FUNCIONARIO INT4, p_ID_NIVEL INT4, p_PASSWORD_PGESTAO TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE ACESSO_PGESTAO
    SET ID_FUNCIONARIO = p_ID_FUNCIONARIO, ID_NIVEL = p_ID_NIVEL, PASSWORD_PGESTAO = p_PASSWORD_PGESTAO
    WHERE ID_UTILPGESTAO = p_ID_UTILPGESTAO;
    RAISE NOTICE 'Acesso à plataforma de gestão atualizado';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Acesso_pgestao_delete(p_ID_UTILPGESTAO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM ACESSO_PGESTAO
    WHERE ID_UTILPGESTAO = p_ID_UTILPGESTAO;
    RAISE NOTICE 'Acesso à plataforma de gestão eliminado';
END;
$$;

-- List
CREATE OR REPLACE PROCEDURE sp_Acesso_pgestao_list()
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_FUNCIONARIO, ID_NIVEL, PASSWORD_PGESTAO
    FROM ACESSO_PGESTAO;
END;
$$;
