-- Create
CREATE OR REPLACE PROCEDURE sp_Armazem_create(p_NOME_ARMAZEM TEXT, p_MORADA_ARMAZEM TEXT, p_EMAIL_ARMAZEM TEXT, p_CONTACTO_ARMAZEM NUMERIC, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO ARMAZEM(NOME_ARMAZEM, MORADA_ARMAZEM, EMAIL_ARMAZEM, CONTACTO_ARMAZEM, ID_FUNCIONARIO)
    VALUES (p_NOME_ARMAZEM, p_MORADA_ARMAZEM, p_EMAIL_ARMAZEM, p_CONTACTO_ARMAZEM, p_ID_FUNCIONARIO);
    RAISE NOTICE 'Armazém criado';
END;
$$;



-- Update
CREATE OR REPLACE PROCEDURE sp_Armazem_update(p_ID_ARMAZEM INTEGER, p_NOME_ARMAZEM TEXT, p_MORADA_ARMAZEM TEXT, p_EMAIL_ARMAZEM TEXT, p_CONTACTO_ARMAZEM NUMERIC, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE ARMAZEM
    SET NOME_ARMAZEM = p_NOME_ARMAZEM, MORADA_ARMAZEM = p_MORADA_ARMAZEM, EMAIL_ARMAZEM = p_EMAIL_ARMAZEM, CONTACTO_ARMAZEM = p_CONTACTO_ARMAZEM, ID_FUNCIONARIO = p_ID_FUNCIONARIO
    WHERE ID_ARMAZEM = p_ID_ARMAZEM;
    RAISE NOTICE 'Armazém atualizado';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Armazem_delete(p_ID_ARMAZEM INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM ARMAZEM
    WHERE ID_ARMAZEM = p_ID_ARMAZEM;
    RAISE NOTICE 'Armazém eliminado';
END;
$$;

