-- Create
CREATE OR REPLACE PROCEDURE sp_CATEGORIACOMPONENTES_create(p_NOME_CATCOMPONENTES TEXT, p_DESCRICAO_CATCOMPONENTES TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO CATEGORIACOMPONENTES(NOME_CATCOMPONENTES, DESCRICAO_CATCOMPONENTES)
    VALUES (p_NOME_CATCOMPONENTES, p_DESCRICAO_CATCOMPONENTES);
    RAISE NOTICE 'Categoria de componentes criada';
END;
$$;



-- Update
CREATE OR REPLACE PROCEDURE sp_CATEGORIACOMPONENTES_update(p_ID_CATCOMPONENTES INTEGER, p_NOME_CATCOMPONENTES TEXT, p_DESCRICAO_CATCOMPONENTES TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE CATEGORIACOMPONENTES
    SET NOME_CATCOMPONENTES = p_NOME_CATCOMPONENTES, DESCRICAO_CATCOMPONENTES = p_DESCRICAO_CATCOMPONENTES
    WHERE ID_CATCOMPONENTES = p_ID_CATCOMPONENTES;
    RAISE NOTICE 'Categoria de componentes atualizada';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_CATEGORIACOMPONENTES_delete(p_ID_CATCOMPONENTES INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM CATEGORIACOMPONENTES
    WHERE ID_CATCOMPONENTES = p_ID_CATCOMPONENTES;
    RAISE NOTICE 'Categoria de componentes eliminada';
END;
$$;

