-- Create
CREATE OR REPLACE PROCEDURE sp_Encomendas_create(p_ID_GUIACOMPRAS INT4, p_DATA_ENCOMENDA DATE, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO ENCOMENDAS(ID_GUIACOMPRAS, DATA_ENCOMENDA, ID_FUNCIONARIO)
    VALUES (p_ID_GUIACOMPRAS, p_DATA_ENCOMENDA, p_ID_FUNCIONARIO);
    RAISE NOTICE 'Encomenda criada';
END;
$$;

-- Read
CREATE OR REPLACE PROCEDURE sp_Encomendas_read(p_ID_ENCOMENDA INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_GUIACOMPRAS, DATA_ENCOMENDA, ID_FUNCIONARIO
    FROM ENCOMENDAS
    WHERE ID_ENCOMENDA = p_ID_ENCOMENDA;
END;
$$;

-- Update
CREATE OR REPLACE PROCEDURE sp_Encomendas_update(p_ID_ENCOMENDA INTEGER, p_ID_GUIACOMPRAS INT4, p_DATA_ENCOMENDA DATE, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE ENCOMENDAS
    SET ID_GUIACOMPRAS = p_ID_GUIACOMPRAS, DATA_ENCOMENDA = p_DATA_ENCOMENDA, ID_FUNCIONARIO = p_ID_FUNCIONARIO
    WHERE ID_ENCOMENDA = p_ID_ENCOMENDA;
    RAISE NOTICE 'Encomenda atualizada';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Encomendas_delete(p_ID_ENCOMENDA INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM ENCOMENDAS
    WHERE ID_ENCOMENDA = p_ID_ENCOMENDA;
    RAISE NOTICE 'Encomenda eliminada';
END;
$$;
