-- Create
CREATE OR REPLACE PROCEDURE sp_Equipamentos_fatura_create(p_ID_FATURA INT4, p_ID_EQUIP INT4, p_QUANTIDADE_EQUIPFATURA INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO EQUIPAMENTOS_FATURA(ID_FATURA, ID_EQUIP, QUANTIDADE_EQUIPFATURA)
    VALUES (p_ID_FATURA, p_ID_EQUIP, p_QUANTIDADE_EQUIPFATURA);
    RAISE NOTICE 'Equipamento fatura criado';
END;
$$;

-- Read
CREATE OR REPLACE PROCEDURE sp_Equipamentos_fatura_read(p_ID_FATURA INT4, p_ID_EQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT QUANTIDADE_EQUIPFATURA
    FROM EQUIPAMENTOS_FATURA
    WHERE ID_FATURA = p_ID_FATURA AND ID_EQUIP = p_ID_EQUIP;
END;
$$;

-- Update
CREATE OR REPLACE PROCEDURE sp_Equipamentos_fatura_update(p_ID_FATURA INT4, p_ID_EQUIP INT4, p_QUANTIDADE_EQUIPFATURA INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE EQUIPAMENTOS_FATURA
    SET QUANTIDADE_EQUIPFATURA = p_QUANTIDADE_EQUIPFATURA
    WHERE ID_FATURA = p_ID_FATURA AND ID_EQUIP = p_ID_EQUIP;
    RAISE NOTICE 'Equipamento fatura atualizado';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Equipamentos_fatura_delete(p_ID_FATURA INT4, p_ID_EQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM EQUIPAMENTOS_FATURA
    WHERE ID_FATURA = p_ID_FATURA AND ID_EQUIP = p_ID_EQUIP;
    RAISE NOTICE 'Equipamento fatura eliminado';
END;
$$;

-- List
CREATE OR REPLACE PROCEDURE sp_Equipamentos_fatura_list()
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_FATURA, ID_EQUIP, QUANTIDADE_EQUIPFATURA
    FROM EQUIPAMENTOS_FATURA;
END;
$$;
