-- Create
CREATE OR REPLACE PROCEDURE sp_Equipamentos_create(p_ID_TIPOEQUIP INT4, p_ID_MO INT4, p_NOME_EQUIP TEXT, p_DESC_EQUIP TEXT, p_CUSTO_EQUIP DECIMAL(10,2))
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO EQUIPAMENTOS(ID_TIPOEQUIP, ID_MO, NOME_EQUIP, DESC_EQUIP, CUSTO_EQUIP)
    VALUES (p_ID_TIPOEQUIP, p_ID_MO, p_NOME_EQUIP, p_DESC_EQUIP, p_CUSTO_EQUIP);
    RAISE NOTICE 'Equipamento criado';
END;
$$;

-- Read
CREATE OR REPLACE PROCEDURE sp_Equipamentos_read(p_ID_EQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_TIPOEQUIP, ID_MO, NOME_EQUIP, DESC_EQUIP, CUSTO_EQUIP
    FROM EQUIPAMENTOS
    WHERE ID_EQUIP = p_ID_EQUIP;
END;
$$;

-- Update
CREATE OR REPLACE PROCEDURE sp_Equipamentos_update(p_ID_EQUIP INT4, p_ID_TIPOEQUIP INT4, p_ID_MO INT4, p_NOME_EQUIP TEXT, p_DESC_EQUIP TEXT, p_CUSTO_EQUIP DECIMAL(10,2))
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE EQUIPAMENTOS
    SET ID_TIPOEQUIP = p_ID_TIPOEQUIP, ID_MO = p_ID_MO, NOME_EQUIP = p_NOME_EQUIP, DESC_EQUIP = p_DESC_EQUIP, CUSTO_EQUIP = p_CUSTO_EQUIP
    WHERE ID_EQUIP = p_ID_EQUIP;
    RAISE NOTICE 'Equipamento atualizado';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Equipamentos_delete(p_ID_EQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM EQUIPAMENTOS
    WHERE ID_EQUIP = p_ID_EQUIP;
    RAISE NOTICE 'Equipamento eliminado';
END;
$$;

-- List
CREATE OR REPLACE PROCEDURE sp_Equipamentos_list()
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_TIPOEQUIP, ID_MO, NOME_EQUIP, DESC_EQUIP, CUSTO_EQUIP
    FROM EQUIPAMENTOS;
END;
$$;
