-- Create
CREATE OR REPLACE PROCEDURE sp_Funcionarios_create(p_NOME TEXT, p_DATANASC DATE, p_NIF INT4, p_EMAIL TEXT, p_CONTACTO NUMERIC, p_MORADA TEXT, p_CARGO TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO FUNCIONARIOS(NOME, DATANASC, NIF, EMAIL, CONTACTO, MORADA, CARGO)
    VALUES (p_NOME, p_DATANASC, p_NIF, p_EMAIL, p_CONTACTO, p_MORADA, p_CARGO);
    RAISE NOTICE 'Funcionário criado';
END;
$$;


-- Update
CREATE OR REPLACE PROCEDURE sp_Funcionarios_update(p_ID_FUNCIONARIO INTEGER, p_NOME TEXT, p_DATANASC DATE, p_NIF INT4, p_EMAIL TEXT, p_CONTACTO NUMERIC, p_MORADA TEXT, p_CARGO TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE FUNCIONARIOS
    SET NOME = p_NOME, DATANASC = p_DATANASC, NIF = p_NIF, EMAIL = p_EMAIL, CONTACTO = p_CONTACTO, MORADA = p_MORADA, CARGO = p_CARGO
    WHERE ID_FUNCIONARIO = p_ID_FUNCIONARIO;
    RAISE NOTICE 'Funcionário atualizado';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Funcionarios_delete(p_ID_FUNCIONARIO INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM FUNCIONARIOS
    WHERE ID_FUNCIONARIO = p_ID_FUNCIONARIO;
    RAISE NOTICE 'Funcionário eliminado';
END;
$$;

