-- Create
CREATE OR REPLACE PROCEDURE sp_Guiaremessacompras_create(p_ID_ARMAZEM INT4, p_DATA_GUIACOMPRAS DATE, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO GUIAREMESSACOMPRAS(ID_ARMAZEM, DATA_GUIACOMPRAS, ID_FUNCIONARIO)
    VALUES (p_ID_ARMAZEM, p_DATA_GUIACOMPRAS, p_ID_FUNCIONARIO);
    RAISE NOTICE 'Guia de remessa de compras criada';
END;
$$;

-- Read
CREATE OR REPLACE PROCEDURE sp_Guiaremessacompras_read(p_ID_GUIACOMPRAS INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_ARMAZEM, DATA_GUIACOMPRAS, ID_FUNCIONARIO
    FROM GUIAREMESSACOMPRAS
    WHERE ID_GUIACOMPRAS = p_ID_GUIACOMPRAS;
END;
$$;

-- Update
CREATE OR REPLACE PROCEDURE sp_Guiaremessacompras_update(p_ID_GUIACOMPRAS INTEGER, p_ID_ARMAZEM INT4, p_DATA_GUIACOMPRAS DATE, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE GUIAREMESSACOMPRAS
    SET ID_ARMAZEM = p_ID_ARMAZEM, DATA_GUIACOMPRAS = p_DATA_GUIACOMPRAS, ID_FUNCIONARIO = p_ID_FUNCIONARIO
    WHERE ID_GUIACOMPRAS = p_ID_GUIACOMPRAS;
    RAISE NOTICE 'Guia de remessa de compras atualizada';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Guiaremessacompras_delete(p_ID_GUIACOMPRAS INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM GUIAREMESSACOMPRAS
    WHERE ID_GUIACOMPRAS = p_ID_GUIACOMPRAS;
    RAISE NOTICE 'Guia de remessa de compras eliminada';
END;
$$;

-- List
CREATE OR REPLACE PROCEDURE sp_Guiaremessacompras_list()
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_ARMAZEM, DATA_GUIACOMPRAS, ID_FUNCIONARIO
    FROM GUIAREMESSACOMPRAS;
END;
$$;
