-- Create
CREATE OR REPLACE PROCEDURE sp_Guiaremessavendas_create(p_ID_ARMAZEM INT4, p_DATA_GUIAVENDAS DATE, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO GUIAREMESSAVENDAS(ID_ARMAZEM, DATA_GUIAVENDAS, ID_FUNCIONARIO)
    VALUES (p_ID_ARMAZEM, p_DATA_GUIAVENDAS, p_ID_FUNCIONARIO);
    RAISE NOTICE 'Guia de remessa de vendas criada';
END;
$$;

-- Read
CREATE OR REPLACE PROCEDURE sp_Guiaremessavendas_read(p_ID_GUIAVENDAS INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_ARMAZEM, DATA_GUIAVENDAS, ID_FUNCIONARIO
    FROM GUIAREMESSAVENDAS
    WHERE ID_GUIAVENDAS = p_ID_GUIAVENDAS;
END;
$$;

-- Update
CREATE OR REPLACE PROCEDURE sp_Guiaremessavendas_update(p_ID_GUIAVENDAS INT4, p_ID_ARMAZEM INT4, p_DATA_GUIAVENDAS DATE, p_ID_FUNCIONARIO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE GUIAREMESSAVENDAS
    SET ID_ARMAZEM = p_ID_ARMAZEM, DATA_GUIAVENDAS = p_DATA_GUIAVENDAS, ID_FUNCIONARIO = p_ID_FUNCIONARIO
    WHERE ID_GUIAVENDAS = p_ID_GUIAVENDAS;
    RAISE NOTICE 'Guia de remessa de vendas atualizada';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Guiaremessavendas_delete(p_ID_GUIAVENDAS INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM GUIAREMESSAVENDAS
    WHERE ID_GUIAVENDAS = p_ID_GUIAVENDAS;
    RAISE NOTICE 'Guia de remessa de vendas eliminada';
END;
$$;

-- List
CREATE OR REPLACE PROCEDURE sp_Guiaremessavendas_list()
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY SELECT ID_ARMAZEM, DATA_GUIAVENDAS, ID_FUNCIONARIO
    FROM GUIAREMESSAVENDAS;
END;
$$;
