-- Create
CREATE OR REPLACE PROCEDURE sp_Producao_diaria_create(p_DATA_PRODUCAO DATE, p_ID_ARMAZEM INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO PRODUCAO_DIARIA(DATA_PRODUCAO, ID_ARMAZEM)
    VALUES (p_DATA_PRODUCAO, p_ID_ARMAZEM);
    RAISE NOTICE 'Produção diária criada';
END;
$$;



-- Update
CREATE OR REPLACE PROCEDURE sp_Producao_diaria_update(p_ID_PRODUCAO INT4, p_DATA_PRODUCAO DATE, p_ID_ARMAZEM INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE PRODUCAO_DIARIA
    SET DATA_PRODUCAO = p_DATA_PRODUCAO, ID_ARMAZEM = p_ID_ARMAZEM
    WHERE ID_PRODUCAO = p_ID_PRODUCAO;
    RAISE NOTICE 'Produção diária atualizada';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Producao_diaria_delete(p_ID_PRODUCAO INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM PRODUCAO_DIARIA
    WHERE ID_PRODUCAO = p_ID_PRODUCAO;
    RAISE NOTICE 'Produção diária eliminada';
END;
$$;

