-- Create
CREATE OR REPLACE PROCEDURE sp_Stockequipamentos_create(p_ID_ARMAZEM INT4, p_ID_EQUIP INT4, p_QUANTIDADE_STOCKEQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO STOCKEQUIPAMENTOS(ID_ARMAZEM, ID_EQUIP, QUANTIDADE_STOCKEQUIP)
    VALUES (p_ID_ARMAZEM, p_ID_EQUIP, p_QUANTIDADE_STOCKEQUIP);
    RAISE NOTICE 'Stock equipamento criado';
END;
$$;


-- Update
CREATE OR REPLACE PROCEDURE sp_Stockequipamentos_update(p_ID_ARMAZEM INT4, p_ID_EQUIP INT4, p_QUANTIDADE_STOCKEQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE STOCKEQUIPAMENTOS
    SET QUANTIDADE_STOCKEQUIP = p_QUANTIDADE_STOCKEQUIP
    WHERE ID_ARMAZEM = p_ID_ARMAZEM AND ID_EQUIP = p_ID_EQUIP;
    RAISE NOTICE 'Stock equipamento atualizado';
END;
$$;

-- Delete
CREATE OR REPLACE PROCEDURE sp_Stockequipamentos_delete(p_ID_ARMAZEM INT4, p_ID_EQUIP INT4)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM STOCKEQUIPAMENTOS
    WHERE ID_ARMAZEM = p_ID_ARMAZEM AND ID_EQUIP = p_ID_EQUIP;
    RAISE NOTICE 'Stock equipamento eliminado';
END;
$$;
